---
title: "FA23 STAT351: Schedule"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(knitr)
library(kableExtra)
```


```{r, echo=F}

sched_table<-tibble(Date=c("Sep 05", "Sep 12", "Sep 19","Sep 26", "Oct 03", "Oct 10", "Oct 17", "Oct 24", "Oct 31", "Nov 07", "Nov 14", "Nov 21", "Nov 28", "Dec 05", "Dec 12"),
          slides= c( cell_spec("Slides", "html", link = "Week1slides.pdf"),
              cell_spec("Slides", "html", link = "Week2slides.pdf"),
             "______",
              cell_spec("Slides", "html", link = "Week4slides.pdf"),
              cell_spec("Slides", "html", link = "Week5slides.pdf"),
             "______",
              cell_spec("Slides", "html", link = "Week6slides.pdf"),
              cell_spec("Slides", "html", link = "Week7slides.pdf"),
             "Exam 1",
              cell_spec("Slides", "html", link = "Week8slides.pdf"),
              cell_spec("Slides", "html", link = "Week9slides.pdf"),
              cell_spec("Slides", "html", link = "Week10slides.pdf"),
              cell_spec("Slides", "html", link = "Week11slides.pdf"),
             "slides",
             "slides"),


Worksheet = c( cell_spec("Worksheet 1", "html", link = "Worksheet1.pdf"),
             cell_spec("Worksheet 2", "html", link = "Worksheet2.pdf"),
             cell_spec("Quiz 1 Review", "html", link = "Quiz1Review.pdf"),
             cell_spec("Worksheet 3", "html", link = "Worksheet3.pdf"),
             cell_spec("Worksheet 4", "html", link = "Worksheet4.pdf"),
             cell_spec("Quiz 2 Review", "html", link = "Quiz2Review.pdf"),
             cell_spec("Worksheet 5", "html", link = "Worksheet5.pdf"),
             cell_spec("Worksheet 6", "html", link = "Worksheet6.pdf"),
            "___________",
             cell_spec("Worksheet 7", "html", link = "Worksheet7.pdf"),
             cell_spec("Worksheet 8", "html", link = "Worksheet8.pdf"),
             cell_spec("Worksheet 9", "html", link = "Worksheet9.pdf"),
             cell_spec("Worksheet 9", "html", link = "Worksheet10.pdf"),
            "Worksheet 11",
            "Worksheet 12"
            ),

`Worksheet solution` = c( cell_spec("Worksheet 1", "html", link = "worksheet1_solution.pdf"),
           cell_spec("Worksheet 2", "html", link = "worksheet2_solution.pdf"),
           cell_spec("Quiz 1 review (in-class work)", "html", link = "Quiz1Reviewanotated.pdf"),
           cell_spec("Worksheet 3", "html", link = "worksheet3_solution.pdf"),
           cell_spec("Worksheet 4", "html", link = "worksheet4_solution.pdf"),
           cell_spec("Quiz 2 review (in-class work)", "html", link = "Quiz2Reviewanotated.pdf"),
           cell_spec("Worksheet 5", "html", link = "worksheet5_solution.pdf"),
           cell_spec("Worksheet 6", "html", link = "worksheet6_solution.pdf"),
           "___________",
           cell_spec("Worksheet 7", "html", link = "worksheet7_solution.pdf"),
           cell_spec("Worksheet 8", "html", link = "worksheet8_solution.pdf"),
           cell_spec("Worksheet 9", "html", link = "worksheet9_solution.pdf"),
           cell_spec("Worksheet 10", "html", link = "worksheet10_solution.pdf"),
           "Worksheet 11",
           "Worksheet 12"
            ),
              
          Note = c("______",
                   "Chp 2 HW due on Sep 17th",
                   "Chp 3 HW due on Sep 24th and Quiz 1 on Sep 23-24th",
                   "______",
                   "______"     ,
                    "Chp4 HW due on Oct 15th and Quiz 2 on Oct 14-15th",
                   cell_spec("Exam 1 review", "html", link = "2023Exam1R.pdf"),            
                   cell_spec("Exam 1 review final answers", "html", link = "2023Exam1R_Answer.pdf"),
                   "Exam 1 (during discussion)",
                   "Chp 7 HW due on Nov 12th",
                   "Quiz 3 on Nov 18-19th",
                   "Chp 8 HW due on Oct 26th",
                   "______",
                   "Exam 2 online and Chp 9 HW due on Dec 10th",
                   "Last day of classes"))

sched_table %>% 
  kable("html", escape = FALSE) %>%
    column_spec (1:5,border_left = T, border_right = T) %>%
    kable_styling()

```
