---
title: "Chapter 9 (Part 2)"
author: "Fred Azizi"
date: "2023-04-25"
fontsize: 9pt
output: 
   beamer_presentation:
     theme: "Frankfurt"
     colortheme: "crane"
header-includes:
  - \setbeamertemplate{navigation symbols}{}
  - \setbeamertemplate{footline}[page number]
  - \usepackage{xcolor}
  - \usepackage{adjustbox}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Quick review (1)

**Central Limit Theorem**

 **The sampling distribution of the mean of a random sample drawn from any population is approximately normal for a sufficiently large sample size.**
 
 * \textcolor{red}{Mean} of distribution of the sampling mean is the same as mean of the population, $\mu_{\bar{X}}=\mu$.
 * Standard deviation of the sampling distribution (\textcolor{red}{standard error} of the mean is $\sigma_{\bar{X}}=\frac{\sigma}{\sqrt n}$.
 * $\bar{X} \sim N(\mu,\frac{\sigma}{\sqrt n})$.
 * Finite population correction for standard error: 
 $$\sigma_{\bar{X}}=\sqrt{\frac{N-n}{N-1}} \cdot \frac{\sigma}{\sqrt{n}}$$
    + Rule of thumb: Use for population that is at least 20 times larger than the sample size

## Quick review (2)

**Goal: Estimating population proportion (or number of) of successes**

Examples: Proportion of people voting for a certain candidate, Number of defectives in a production system, etc. 

* Our estimate: $\hat{p}= \frac{x}{n}$ where $x$ is the number of successes in sample and $n$ is sample size.

* Distribution of $\hat{p}$ using CLT:
   + Under the conditions that $np\geq 5$ and $n(1-p) \geq 5$, by CLT, $\hat{p}\sim N\left(\mu=p, \sigma=\sqrt{\frac{p(1-p)}{n}}\right)$.
   + For calculation of $\sigma$ above, if $p$ is not known, replace it with $\hat{p}$. 
 
## Quick review (3)

**Approximation of Binomial Probability using Normal distribution**

* If $X\sim \text{Bin}(n,p)$, then We can use $Y\sim N\left(np, \sqrt{np(1-p)}\right)$ to approximate probabilities

* $P(X=x)\approx P(x-0.5\leq Y \leq x+0.5)$ (0.5 is **continuity correction factor**)

* $P(X\leq x) \approx P(Y< x+0.5)$

## Quick review (4)

Distribution of difference between two sample means. Now we are interested in $\mu_1-\mu_2$.

* Using CLT and the fact that difference of Normally distributed RVs is Normal, $\bar{X}_1-\bar{X}_2\sim N\left(\mu=\mu_1-\mu_2, \sigma_{\bar{X}_1-\bar{X}_2}=\sqrt{\frac{\sigma_1^2}{n_1}+\frac{\sigma_2^2}{n_2}}\right)$.
* To use CLT, $n_1\geq30$ and $n_2\geq30$. If this is not satisfied, we need Normal populations for both samples.      