---
title: "Chapter 4 review"
author: "Fred Azizi"
date: "2022-10-03"
output: 
   beamer_presentation:
     theme: "Frankfurt"
     colortheme: "crane"
header-includes:
- \usepackage{xcolor}
- \usepackage{adjustbox}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Quick review (1)

Measures of relative standing: 

-   Percentile: The value for which $P$ percent are less than that value and $(100 - P)\%$ are greater than that value.
    -   Location of percentile in ordered data: $L_P=(n+1) \frac{P}{100}$.

Measure of variability:

- Variance: $s^2=\frac{\sum_{i=1}^n\left(x_i-\bar{x}\right)^2}{\color{red}{n-1}}$.

- Standard deviation: $s=\sqrt{s^2}$.

- Coefficient of variation: cv $=\frac{s}{\bar{x}}$.

## Quick review (2)

Measures of Linear Relationship:

- Covariance: $s_{x y}=\frac{\sum_{i=1}^n\left(x_i-\bar{x}\right)\left(y_i-\bar{y}\right)}{n-1}$.

- Correlation: $r=\frac{s_{x y}}{s_{x} s_y}$.

- Least Square line: $\hat{y}=b_0+b_1 x$ where $b_1=\frac{s_{x y}}{s_x^2}$ and $b_0=\bar{y}-b_1 \bar{x}$. 

- Coefficient of determination $r^2$.

## Quick review (3)

Given a sample space $S=\left\{O_1, O_2, \ldots, O_k\right\}$

- $0 \leq P\left(O_i\right) \leq 1$ for each $i$

- $\sum_{i=1}^k P\left(O_i\right)=1$.

## Quick review (4)

- Mutually exclusive: No two outcomes can occur at the same time.

- Exhaustive events: All possible outcomes are included.

- Intersection of Events $A$ and $B$: the event that occurs when both $A$ and $B$ occur. 

- Union of Events $A$ and $B$ is the event that occurs when either $A$ or $B$ or **both **occur. It is denoted as
A or $B$.

- Conditional Probability: The probability of event $A$ given event $B$ is
$$
P(A \mid B)=\frac{P(A \text { and } B)}{P(B)}
$$
- Independent Events: $A$ and $B$ are said to be independent if $P(A \mid B)=P(A)$ or $P(B \mid A)=P(B)$.


## Quick review (5)

- Complement Rule: $P\left(A^C\right)=1-P(A)$.

- Multiplication Rule: $P(A \text { and } B)=P(B) P(A \mid B)$.

- Addition Rule: $P(A$ or $B)=P(A)+P(B)-P(A$ and $B)$
