---
title: "Chapter 6 Review"
author: "Fred Azizi"
date: "2023-10-17"
output: 
   beamer_presentation:
     theme: "Frankfurt"
     colortheme: "crane"
header-includes:
- \usepackage{xcolor}
- \usepackage{adjustbox}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Quick review (1)

Given a sample space $S=\left\{O_1, O_2, \ldots, O_k\right\}$

- $0 \leq P\left(O_i\right) \leq 1$ for each $i$

- $\sum_{i=1}^k P\left(O_i\right)=1$.

## Quick review (2)

- Mutually exclusive: No two outcomes can occur at the same time.

- Exhaustive events: All possible outcomes are included.

- Intersection of Events $A$ and $B$: the event that occurs when both $A$ and $B$ occur. 

- Union of Events $A$ and $B$ is the event that occurs when either $A$ or $B$ or **both **occur. It is denoted as
A or $B$.

- Conditional Probability: The probability of event $A$ given event $B$ is
$$
P(A \mid B)=\frac{P(A \text { and } B)}{P(B)}
$$
- Independent Events: $A$ and $B$ are said to be independent if $P(A \mid B)=P(A)$ or $P(B \mid A)=P(B)$.


## Quick review (3)

- Complement Rule: $P\left(A^C\right)=1-P(A)$.

- Multiplication Rule: $P(A \text { and } B)=P(B) P(A \mid B)$.

- Addition Rule: $P(A$ or $B)=P(A)+P(B)-P(A$ and $B)$

## Quick review (4)

-   Bayes Rule: $P\left(A_i \mid B\right)=\frac{P\left(A_i\right) P\left(B \mid A_i\right)}{P\left(A_1\right) P\left(B \mid A_1\right)+P\left(A_2\right) P\left(B \mid A_2\right)+\cdots+P\left(A_k\right) P\left(B \mid A_k\right)}$.

-   Probability Trees: Helps with showing the events in an experiment by lines using conditionality.

-   Joint Probabilities table: Shows the joint probabilities across different levels of categories.

-   Marginal probabilities: From Joint distribution table, computed by adding across rows or down columns.

## Quick review (5)

Additional terminologies (for homework only):

For question 14 of homework we define: $\mathrm{C}=$ an individual has the genetic condition, $\mathrm{C}^{\mathrm{c}}=$ an individual does not have the genetic condition, PT $=$ a positive blood test, and NT $=$ a negative blood test.

- $P(P T \mid C)$ is  called the **sensitivity**.

- $P\left(N T \mid C^C\right)$ is called the **specificity**

- $P(C \mid P T)$ is called the **positive predictive value**.

- $P\left(C^C \mid N T\right)$ is called the **negative predictive value**.

$P(C)$ is given at the beginning of the question. Use **Bayes Rule** to find positive predictive value and negative predictive value