---
title: "Chapter 4"
author: "Fred Azizi"
date: "2023-09-26"
output: 
   beamer_presentation:
     theme: "Frankfurt"
     colortheme: "crane"
header-includes:
- \usepackage{xcolor}
- \usepackage{adjustbox}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Quick review

 measure of central tendency: 
 
* Compute the (Arithmetic) Mean to 
   + Describe the central location of a single set of interval and ratio data

* Compute the Median to
   + Describe the central location of a single set of interval and ratio or ordinal data

* Compute the Mode to 
   + Describe a single set of nominal, ordinal, interval or ratio data

## Quick review (2)

Measures of relative standing: \textcolor{red}{Interval-Ratio-Ordinal data.}

-   Percentile: The value for which $P$ percent are less than that value and $(100 - P)\%$ are greater than that value.
    -   Location of percentile in ordered data: $L_P=(n+1) \frac{P}{100}$.
-   Quartiles: Special case of percentiles$\rightarrow$ 25th ($Q_1$), 50th (Median-$Q_2$), and 75th percentiles($Q_3$).

## Quick review (3)

Measure of variability:

- Range: $\max-\min$.
-   $\text {Interquartile range }=Q_3-Q_1$.
- Variance: $s^2=\frac{\sum_{i=1}^n\left(x_i-\bar{x}\right)^2}{\color{red}{n-1}}$.
   * What if we have **Population**'s data?
- Standard deviation: $s=\sqrt{s^2}$.
   * What if we have **Population**'s data?
- Coefficient of variation: cv $=\frac{s}{\bar{x}}$.

## Quick review (4)

Measures of Linear Relationship:

- Covariance: $s_{x y}=\frac{\sum_{i=1}^n\left(x_i-\bar{x}\right)\left(y_i-\bar{y}\right)}{n-1}$.

- Correlation: $r=\frac{s_{x y}}{s_{x} s_y}$.

- Least Square line: $\hat{y}=b_0+b_1 x$ where $b_1=\frac{s_{x y}}{s_x^2}$ and $b_0=\bar{y}-b_1 \bar{x}$. 

- Coefficient of determination $r^2$.
