---
title: "Chapter 7 (Part 2)"
author: "Fred Azizi"
date: "2023-04-04"
output: 
   beamer_presentation:
     theme: "Frankfurt"
     colortheme: "crane"
header-includes:
- \usepackage{xcolor}
- \usepackage{adjustbox}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Quick review 

Binomial random variable

* The binomial experiment consists of a **fixed number of trials** ($n$).

* Each trial has **two possible outcomes**: S/F.

* The probability of success is $p$ (**fixed**). The probability of failure is 1-$p$ (fixed). 

* The trials are **independent**.

* $P(x)= nCx \; \;p^x (1-p)^{n-x}$.

* $E(x)=np$, $Var(x)=np(1-p)$.

## Quick review 

The Poisson  random  variable 

* Defined as  **number  of  successes**  that  occur  in  a  period of time or an interval of space.

* The number of successes that occur in any interval is **independent** of the number of successes that occur in any other interval.

* The probability of a success in an interval is the same for all equal-size intervals.

* The probability of a success in an interval is **proportional to the size of the interval**.

* $P(x)=\frac{e^{-\mu}\mu^x}{x!}$ where $\mu$ is the mean number of successes in the interval or region.

* $E(x)=\mu$, $Var(x)=\mu$.