---
title: "Worksheet 12"
author: "Fred Azizi"
date: "2023-12-12"
header-include:
  - \usepackage[utf8]{inputenc}
  - \usepackage[T1]{fontenc}
  - \usepackage{amsmath}
  - \usepackage{amsfonts}
  - \usepackage{amssymb}
  - \usepackage[version=4]{mhchem}
  - \usepackage{stmaryrd}
  - \usepackage{graphicx}
  - \usepackage[export]{adjustbox}
output: pdf_document
---

1. A pollster in Maryland wants to estimate the proportion (to within 0.05) of registered voters that are Socialists, using 95% confidence. What sample size should he use, if he has no previous ideas about the proportion of Socialists in Maryland?


\newpage

2. An electronics retailer is interested in studying the incomes of consumers in a particular area. The population standard deviation is known to be \$5,000. What sample size would the researcher need to use for a 90% confidence interval if the difference between UCL and LCL should not be more than \$1000? Hint: consider the relationship between the width of the confidence interval and the margin of error.

\newpage


3.  A random sample of 49 marketing brochures was drawn, and the number of hours to design each brochure was recorded. The population of the number of hours required is normally distributed, with a standard deviation of one hour. The sample average was 6.3 hours. Is there evidence to support the hypothesis that it takes more than 6 hours to design a marketing brochure? Use $\alpha=0.05$.

> a. What are the hypotheses being tested?

> b. What is the test statistic?

> c. What is the rejection region?

> d. Can you conclude at the $1 \%$ level of significance that it takes more than 3 hours to design a marketing brochure? (Answer yes or no).

\newpage


4. Researchers determined that 60 Puffs tissues is the average number of tissues used during a cold. Suppose a random sample of 100 Puffs users yielded the following data on the number of tissues used during a cold: $\bar{x}=52$ and $s=22$. Suppose the alternative we wanted to test was $H_1: \mu<60$. The correct rejection region for $\alpha=0.1$ is:

> a. reject $H_0$ if $t>1.2902$

> b. reject $H_0$ if $t<-1.2902$

> c. reject $H_0$ if $t>0.9442$ or $Z<-0.9442$

> d. reject $H_0$ if $t<-0.9442$