---
title: "Worksheet 4"
author: "Fred Azizi"
date: "2023-10-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1.  The following data has mean income and housing for 10 cities in Florida. Values are in dollars (\$) and rounded to the nearest thousand.

```{=tex}
\begin{center}
\begin{tabular}{|l|l|l|}
\hline City & Income ($\boldsymbol{x})$ & Housing (y) \\
\hline A & 26 & 109 \\
\hline B & 29 & 97 \\
\hline C & 25 & 115 \\
\hline D & 28 & 99 \\
\hline E & 38 & 122 \\
\hline F & 32 & 145 \\
\hline G & 25 & 100 \\
\hline H & 22 & 76 \\
\hline I & 29 & 113 \\
\hline J & 42 & 144 \\
\hline
\end{tabular}
\end{center}
```

> a. Calculate the correlation coefficient between x and y. What can you conclude about the
relationship between the 2 variables?

> b. Calculate the least square line. 

> c. Calculate the coefficient of variation


\newpage

(Extra space for question 1)
 
\newpage

2. A sample of 30 observations has a standard deviation of 4. Find the sum of squared deviations
from the sample mean.

\newpage

3. Following observations are given for two variables.

$$\begin{array}{cc}\mathbf{y} & \mathbf{x} \\ 5 & 2 \\ 8 & 12 \\ 18 & 3 \\ 20 & 6 \\ 22 & 11 \\ 30 & 19 \\ 10 & 18 \\ 7 & 9\end{array}$$

> a. Compute and interpret $\mathrm{P}_{86}$.

> b. Compute and interpret the correlation coefficient.

> c. Draw the relevant diagram for the data above.


\newpage

4. 4 candidates are running for mayor; Adams, Brown, Collins and Dalton  (We assume one of the candidates is going to win, there is no run off). The following probabilities are assigned:

$$P[ \text{Adams wins} ]=0.42 \quad P[ \text{Brown wins} ]=0.09$$

$$P[\text{Collins wins}]=0.27 \quad P[\text{Dalton wins}]=0.22$$

>Determine the probabilities for the following events (use 2 decimal places):

> a. Adams loses.

> b. Either Brown or Dalton wins.

> c. Adams, Brown, or Collins wins.

\newpage
