---
title: "Worksheet 7 Solution"
author: "Fred Azizi"
date: "2023-03-28"
output: pdf_document
---

1. The number of pizzas delivered to university students each month is a random variable with the following probability distribution.

\begin{center}
\begin{tabular}{|l|l|l|l|l|}
\hline $\mathrm{X}$ & 0 & 1 & 2 & 3 \\
\hline $\mathrm{P}(\mathrm{x})$ & $0.1$ & $0.3$ & $0.4$ & $0.2$ \\
\hline
\end{tabular}
\end{center}

> (a) Find $\mathrm{P}(\mathrm{X} \leq 2)$.

> (b) $\mathrm{P}(1 \leq \mathrm{X} \leq 2)$.

> (c) Determine the mean and variance of $X$.

> (d) Suppose $Y=3 X+4$ for each value of $X$,  Calculate the mean and sd of $Y$.


> **\underline{Answer:}**

> (a) $P(X \leq 2)=P(x=0)+P(x=1)+P(x=2)=0.1+0.3+0.4=0.8$

> (b) $P(1 \leq x \leq 2)=P(x=1)+P(x=2)=0.7$

> (c) 

$$
\begin{aligned}
\mu=E(x)=\sum x \cdot P(x)=& 0 \times 0.1+1 \times 0.3+2 \times 0.4+3 \times 0.2=1.7 \\
V(x)=\sum(x-\mu)^{2} \cdot P(x)=&(0-1.7)^{2} \times 0.1+(1-1.7)^{2} \times 0.3+(2-1.7)^{2} \times 0.4 \\
&+3 \times(3-1.7)^{2} \times 0.2=0.81
\end{aligned}
$$


> (d)

$$
\begin{aligned}
&E(y)=E(3 x+4)=3 E(x)+4=3 \times 1 \cdot 7+4=9.1 \\
&V(y)=V(3 x+4)=9 V(x)+0=7.29 \\
&sd(y)=\sqrt{V(y)}=\sqrt{7.29}= 2.7
\end{aligned}
$$
\newpage

2. The number of persons living per household in a city was collected and were summarized. The frequency table is given below:

\begin{center}
\begin{tabular}{|l|l|l|l|l|l|l|l|}
\hline Number of persons & 1 & 2 & 3 & 4 & 5 & 6 & 7 \\
\hline Number of households (millions) & $3.1$ & $4.5$ & $3.8$ & $2.5$ & $2.4$ & $2.5$ & $1.2$ \\
\hline
\end{tabular}
\end{center}

> Define $X$ as the number of people per household.


> (a) Write down the probability distribution of $X$.

> (b) Find $P[X \geq 4]$

> (c) Find $\mathrm{P}[2 \leq \mathrm{X}<4]$

> **\underline{Answer:}**

> (a) 

$$\begin{array}{c|ccccccc}X & 1 & 2 & 3 & 4 & 5 & 6 & 7 \\
\hline
P(x) & 0.155 & 0.225 & 0.19 & 0.125 & 0.12 & 0.125 & 0.06 \end{array}$$

> (b) $P[X \geq 4]=P(x=4)+P(x=5)+P(x=6)+P(x=7)=0.125+0.12+0.125+0.06=0.43$

> (c) $\mathrm{P}[2 \leq X<4] =P(x=2)+P(x=3)=0.225+0.19=0.415$

\newpage

3. Indicate whether each random variable is Binomial, Poisson or neither:

> a. A random variable $X$ counts the number of visits to a webpage in a one-hour period. **Poisson**

> b. A random variable $X$ counts the number of defectives in a sample of 100 stamps. **Binomial**

> c. A random variable $X$ counts the number of hearts drawn from a well shuffled deck of 52 playing cards if 10 cards were drawn one at a time without replacement. **Neither**

> d. A random variable $X$ counts the number of hearts drawn from a well shuffled deck of 52 playing cards if 10 cards were drawn with replacement. **Binomial**


