---
title: "Worksheet 8 Solution"
author: "Fred Azizi"
date: "2023-04-04"
output: pdf_document
---

1. 5 students are giving a make-up quiz. The probability of any of them scoring more than 25 is $0.6$. Let $X$ be the number of students who get over 25.

> a. Identify the distribution of $X$ and its parameters.



> b. What is the probability that none of the students score over 25 ?



> c. What is the probability that at least one of them score over 25 ?


> d. What is the probability that all of them score over 25 ?

> **\underline{Answer:}**

> (a) $X \sim \operatorname{Bin}(n=5, p=0.6)$.

> (b) Using table in the textbook: $P[X=0]=P[X \leqslant 0]=0.0102$.

>> Or you can calculate directly. $P[X=0]= 5C0 \;p^0 (1-p)^{5-0}=0.1024$.

> (c) $P(X \geqslant 1)=1-P(X<1)=1-P(X \leqslant 0)=1-0.0102=0.9898$.

> (d) $P(X=5)=P(X \leqslant 5)-P(X \leqslant 4)=1-0.9222=0.0788$. 

>> Or (again) you can calculte directly: $P[X=5]= 5C5 \;p^5 (1-p)^{5-5}=0.07776$

2. A six-sided die is rolled 6 times. Let $X$ denote the number of times an even number showed up.

> a. What is the probability of the event happening? That is, the probability of getting an even number. 

> b. What distribution will $X$ follow? Identify the parameters.

> c. Calculate $P[X=2]$.

> d. Calculate $P[0 \leq X<3]$

> **\underline{Answer:}**

> (a) That is, the probability of getting an even number. $P(x)=\frac{1}{2}$ (for a single roll of the die).

> (b) $X \sim \operatorname{Bin}(n=6, p=0.5)$

> (c) $P[x=2]=P[x \leqslant 2]-P[x \leqslant 1]=0.3438-0.1094=0.2344$

> (d)
                                                                                                                           
$$                                                                                                                  
\begin{aligned}
P[0 \leqslant x<3] &=P[x \leqslant 2]-P[x <  0]=P[x\leqslant 2]=P[x<3] \\
&=0.3438
\end{aligned}
$$  

3. Acme Corporation's helpdesk gets 4 calls per day on average. They think the number of calls follows a Poisson distribution. 

> a. What is the probability that they get 3 calls or less on a given day?

> b. What is the probability that they get no calls on given day?

> c. What is the probability that they get exactly 3 calls?

> d. What is the expected number of calls in a week? 

> e. What is the standard deviation for calls in a day?

> **\underline{Answer:}**

> (a) Using table: $P[x \leqslant 3]=0.4335$.

> (b) Using table:

$$ 
P[x=0]=P[x \leqslant 0]=0.0183 
$$ 

>> Direct calculation:

$$ 
P[x=0]=\frac{e^{-4} 4^0}{0!}=0.01831564
$$ 

> (c) Using table: $P[x=3]=P[x \leqslant 3]-P[x \leqslant 2]=0.4335-0.2381=0.1954$. 

>> Direct calculation: $P[x=3]=\frac{e^{-4}4^3}{3!}=0.1953668$ 


> (d) Let $Y=\#$ calls per week on average. Then, $Y=7X$. $E(Y)=E(7X)=7E(X)=7\times4=28$.

> (e) $V(X)=\mu=4 \rightarrow SD(x)=\sqrt{4}=2$. 




4. The number of flaws in an optic fiber cable follows a Poisson Distribution. The average number of flaws in $50 \mathrm{~m}$ is $1.5$. Let $x=$  number of  flaws in $50 \mathrm{~m}$.

> a. What is the probability of exactly 2 flaws in $100 \mathrm{~m}$ ?

> b. What is the probability of 3 flaws or less in $150 \mathrm{~m}$ ?


> **\underline{Answer:}**

> (a) Let $Y=$  number of  flaws in $100 \mathrm{~m}$. $Y=2X$. $E(Y)=2E(X)=3$. Using table:

$$
P(Y=2)=P(Y \leqslant 2)-P(Y \leqslant 1)=0.4232-0.1991=0.2241
$$

>> Or, using direct calculation:

$$
P(Y=2)=\frac{e^{-3}3^2}{2!}=0.2240418
$$

> (b) Let $Z=$  number of  flaws in $150 \mathrm{~m}$. $Z=3X$. $E(Z)=3E(X)=4.5$. Using table:

$$
P(Y \leqslant 3)=0.3423
$$


