---
title: "Worksheet 4 Solution"
author: "Fred Azizi"
date: "2023-10-03"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1.  The following data has mean income and housing for 10 cities in Florida. Values are in dollars (\$) and rounded to the nearest thousand.

```{=tex}
\begin{center}
\begin{tabular}{|l|l|l|}
\hline City & Income ($\boldsymbol{x})$ & Housing (y) \\
\hline A & 26 & 109 \\
\hline B & 29 & 97 \\
\hline C & 25 & 115 \\
\hline D & 28 & 99 \\
\hline E & 38 & 122 \\
\hline F & 32 & 145 \\
\hline G & 25 & 100 \\
\hline H & 22 & 76 \\
\hline I & 29 & 113 \\
\hline J & 42 & 144 \\
\hline
\end{tabular}
\end{center}
```

> a. Calculate the correlation coefficient between x and y. What can you conclude about the
relationship between the 2 variables?

> b. Calculate the least square line. 

> c. Calculate the coefficient of variation. 

> **\underline{Answer:}**

> a.

$$
\begin{array}{c|c|c|c|c|c|c}
x_i & y_i & x_i-\bar{x} & \left(x_i-\bar{x}\right)^2 & y_i-\bar{y} & \left(y_i-\bar{y}\right)^2 & \left(x_i-\bar{x}\right)\left(y_i-\bar{y}\right) \\
\hline 26 & 109 & -3.6 & 12.96 & -3 & 9 & 10.8 \\
29 & 97 & -0.6 & 0.36 & -15 & 225 & 9 \\
25 & 115 & -4.6 & 21.16 & 3 & 9 & -13.8 \\
28 & 99 & -1.6 & 2.56 & -13 & 169 & 20.8 \\
38 & 122 & 8.4 & 70.56 & 10 & 100 & 84 \\
32 & 145 & 2.4 & 5.76 & 33 & 1089 & 79.2 \\
25 & 100 & -4.6 & 21.16 & -12 & 144 & 55.2 \\
22 & 76 & -7.6 & 57.76 & -36 & 1296 & 273.6 \\
29 & 113 & -0.6 & 0.36 & 1 & 1 & -0.6 \\
42 & 144 & 12.4 & 153.76 & 32 & 1024 & 396.8 \\
\hline \bar{x}=29.6 & \bar{y}=112 & & 346.4 & & 4066 & 915
\end{array}
$$

$$
\begin{aligned}
&S D(x)=\sqrt{\frac{346.4}{9}}=6.2039 \\
&S D(y)=\sqrt{\frac{4066}{9}}=21.255
\end{aligned}
$$

>> Correlation: $r=\frac{s_{x y}}{s_{x} s_y}=\frac{\frac{1}{9}\times 915}{6.2039\times 21.255}\approx 0.77$. Correlation is greater than zero and close to 1. Hence, as x increases, y increases as well. 

> b.

$$b_1=\frac{s_{x y}}{s_x^2}=\frac{\frac{1}{9}\times 915}{6.2039^2}\approx 2.641491$$

$$b_0=\bar{y}-b_1 \bar{x}=112-2.641491\times29.6 \approx 33.81$$

>> Least square line can be written as $\hat{y}=33.81+2.64 x$.

> c. 

>> coefficient of variation:

$$
\begin{aligned}
&C V(x)=\frac{S_x}{\bar{x}} \times 100=\frac{6.2039}{29.6} \times 100=20.96 \% \\
&C V(y)=\frac{S_y}{\bar{y}} \times 100= \frac{21.255}{112} \times 100=18.98 \%
\end{aligned}
$$
\  


2. A sample of 30 observations has a standard deviation of 4. Find the sum of squared deviations
from the sample mean.

> **\underline{Answer:}**

> We note that $n=30$

\begin{align}
s&=\sqrt{\frac{\sum\left(x_i-\bar{x}\right)^2}{n-1}} \notag\\
4&=\sqrt{\frac{\sum\left(x_i-\bar{x}\right)^2}{30-1}} \notag\\
16&=\frac{\sum\left(x_i-\bar{x}\right)^2}{29} \notag\\ 
& \rightarrow \sum\left(x_i-\bar{x}\right)^2=16\times 29=464 \notag
\end{align}

\  

3. Following observations are given for two variables.

$$\begin{array}{cc}\mathbf{y} & \mathbf{x} \\ 5 & 2 \\ 8 & 12 \\ 18 & 3 \\ 20 & 6 \\ 22 & 11 \\ 30 & 19 \\ 10 & 18 \\ 7 & 9\end{array}$$

> a. Compute and interpret $\mathrm{P}_{86}$.

>> **\underline{Answer:}**

>> ordered $y$:  5  7  8 10 18 20 22 30

>> $L_{86}=(8+1)\frac{86}{100}=7.74$. Therefore, $P_{86}=22+(30-22)\times 0.74 =27.92$

>> ordered $x$: 2  3  6  9 11 12 18 19

>> $L_{86}=(8+1)\frac{86}{100}=7.74$. Therefore, $P_{86}=18+(19-18)\times 0.74 =18.74$

\  

> b. Compute and interpret the correlation coefficient.

>> **\underline{Answer:}**

>>  Using a calculator, the correlation coefficient is approximately 0.345. This indicates a positive and moderately  weak relationship between x and y. 


