---
title: "Worksheet 9"
author: "Fred Azizi"
date: "2023-11-21"
header-include:
  - \usepackage[utf8]{inputenc}
  - \usepackage[T1]{fontenc}
  - \usepackage{amsmath}
  - \usepackage{amsfonts}
  - \usepackage{amssymb}
  - \usepackage[version=4]{mhchem}
  - \usepackage{stmaryrd}
  - \usepackage{graphicx}
  - \usepackage[export]{adjustbox}
output: pdf_document
---

1. The manager of a gas station has observed that the times required by drivers to fill their car's tank and
pay are quite variable. In fact, the times are exponentially distributed with a mean of 7.5 minutes. 

> a. What is the probability that a transaction is completed in less than 5 minutes?

> b. What is the probability that a car can complete the transaction between 5 minutes to 10 minutes?

> c. What is the standard deviation of time until a transaction is completed?

\newpage

2. Find the mean and standard deviations:

> a. $t_5$.

> b. $\chi^2_9$.

> c. $F_{5,15}$. 


\newpage

3. A sample of 40 retirees is drawn at random from a population whose mean age is 72 and standard deviation is 9. 


> a. What is the distribution of the sample mean? 

> b. What is the probability that the mean age of the sample exceeds 73 years old?


> c. What is the probability that the mean age of the sample is at most 73 years old?


> d. What is the probability that the mean age of the sample is between 72 and 75 years old?


> e. What is the probability that a randomly selected retiree is over 73 years old?

\newpage

4. The amount of time spent by American adults playing Poker is Normally distributed with a mean of 4 hours and standard deviation of $1.25$ hours.  If four American adults are randomly selected, find the probability that: 

> a. their average number of hours spent playing Poker is more than  5  hours per week. 

> b. their average number of hours spent playing Poker is between 3 and 6 hours per week.

> c. all four play Poker for more than 5 hours per week.

\newpage


5. To estimate the mean salary for a population of 500 employees, the president of a certain company selected at random a sample of 40 employees.

> a. Would you use the finite population correction factor in calculating the standard error of the sample mean in this case? Explain.


> b. If the population standard deviation is $\$ 800$, compute the standard error both with and without using the finite population correction factor.

\newpage


