---
title: "Worksheet 10"
author: "Fred Azizi"
date: "2023-11-28"
header-include:
  - \usepackage[utf8]{inputenc}
  - \usepackage[T1]{fontenc}
  - \usepackage{amsmath}
  - \usepackage{amsfonts}
  - \usepackage{amssymb}
  - \usepackage[version=4]{mhchem}
  - \usepackage{stmaryrd}
  - \usepackage{graphicx}
  - \usepackage[export]{adjustbox}
output: pdf_document
---


1. Michael is running for president. The proportion of voters who favor Michael is 0.8. A random sample of 100 voters is taken.

> a. What is the distribution of the sample proportion $\hat{p}$ ?

> b. What is the probability that the number of voters in the sample who will vote for Michael will be between 80 and 90?

> c. What is the probability that the number of voters in the sample who will not favor Michael will be more than 16?

\newpage

2. The chairman of the Biology department in a certain college believes that $70 \%$ of the department's graduate internships are given to international students. A random sample of 50 graduate interns is taken.

> a. What is the distribution of the sample proportion? 

> b. What is the probability that the sample proportion $\hat{p}$ is between $0.65$ and $0.73$?

> c. What is the probability that the sample proportion $\hat{p}$ is within $\pm .05$ of the population proportion $p$?

\newpage

3. A professor of statistics noticed that the marks in his course are normally distributed. He has also noticed
that his morning classes average 73%, with a standard deviation of 12% on their final exams. His afternoon
classes average 77%, with a standard deviation of 10%. What is the probability that the mean mark of four randomly selected students from a morning class is greater than the average mark of four randomly selected students from an afternoon class?


\newpage

4. In 200 tosses of a fair coin:

> a. What is the expected value and standard deviation of number of heads?

> b. Use the normal distribution approximation to find the probability of exactly 110 heads.

> c. Use formula of binomial probability to compare the results. 

> d. What is the probability that we have less than or equal to 95 heads? (Use continuity correction factor)

\newpage

5. Suppose that the amount of time teenagers spend weekly working at part-time jobs is normally distributed with a mean of 300 minutes and standard deviation of 36 minutes. Suppose that we sampled this population with a sample size of $n$ and the average of the sample is $\bar{X}_n=360$. 

> a. Construct confidence intervals for the population mean with the following confidence levels and sample sizes:



\begin{center}
\begin{tabular}{|c|c|c|}
\hline
Confidence Level& $\quad \quad n=9 \quad \quad$ & $\quad \quad n=25 \quad \quad$\\
\hline
90\% & & \\
95\% & & \\
99\% & & \\
\hline
\end{tabular}
\end{center}



> b. Does the CI become larger or smaller as the confidence level increases?

> c. Does the Cl become larger or smaller as the sample size increases?

> d. With fixed confidence level and sample size, would the CI become larger/smaller/not change if the sample mean were smaller than 360?

\newpage


6. A sample of 121 cans of coffee showed an average weight of 16 ounces and a standard deviation of $1$ ounces. Find an 80\%  and a 98\% confidence interval for the population mean.



\newpage

7. Among 81 individuals sampled from the population, 24 smokers were observed. 

> a. Develop the $90 \% \mathrm{Cl}$ for the population proportion.

> b. If now you have a new sample of 150 individuals, determine an interval for the number of smokers based on your answer from question 3.


