---
title: "Worksheet 11"
author: "Fred Azizi"
date: "2023-04-25"
header-include:
  - \usepackage[utf8]{inputenc}
  - \usepackage[T1]{fontenc}
  - \usepackage{amsmath}
  - \usepackage{amsfonts}
  - \usepackage{amssymb}
  - \usepackage[version=4]{mhchem}
  - \usepackage{stmaryrd}
  - \usepackage{graphicx}
  - \usepackage[export]{adjustbox}
output: pdf_document
---


1. The amount of time spent by American adults playing Poker is Normally distributed with a mean of 4 hours and standard deviation of $1.25$ hours.  If four American adults are randomly selected, find the probability that: 

> a. their average number of hours spent playing Poker is more than  5  hours per week. 

> b. their average number of hours spent playing Poker is between 3 and 6 hours per week.

> c. all four play Poker for more than 5 hours per week.

\newpage

2. To estimate the mean salary for a population of 500 employees, the president of a certain company selected at random a sample of 40 employees.

> a. Would you use the finite population correction factor in calculating the standard error of the sample mean in this case? Explain.


> b. If the population standard deviation is $\$ 800$, compute the standard error both with and without using the finite population correction factor.

\newpage

3. Michael is running for president. The proportion of voters who favor Michael is 0.8. A random sample of 100 voters is taken.

> a. What is the distribution of the sample proportion $\hat{p}$ ?

> b. What is the probability that the number of voters in the sample who will vote for Michael will be between 80 and 90?

> c. What is the probability that the number of voters in the sample who will not favor Michael will be more than 16?

\newpage

4. The chairman of the Biology department in a certain college believes that $70 \%$ of the department's graduate internships are given to international students. A random sample of 50 graduate interns is taken.

> a. What is the distribution of the sample proportion? 

> b. What is the probability that the sample proportion $\hat{p}$ is between $0.65$ and $0.73$?

> c. What is the probability that the sample proportion $\hat{p}$ is within $\pm .05$ of the population proportion $p$?

\newpage

5. A professor of statistics noticed that the marks in his course are normally distributed. He has also noticed
that his morning classes average 73%, with a standard deviation of 12% on their final exams. His afternoon
classes average 77%, with a standard deviation of 10%. What is the probability that the mean mark of four randomly selected students from a morning class is greater than the average mark of four randomly selected students from an afternoon class?


\newpage

6. In 200 tosses of a fair coin:

> a. What is the expected value and standard deviation of number of heads?

> b. Use the normal distribution approximation to find the probability of exactly 110 heads.

> c. Use formula of binomial probability to compare the results. 

> d. What is the probability that we have less than or equal to 95 heads? (Use continuity correction factor)

