---
title: "Worksheet 12 Solution"
author: "Fred Azizi"
date: "2023-05-02"
header-include:
  - \usepackage[utf8]{inputenc}
  - \usepackage[T1]{fontenc}
  - \usepackage{amsmath}
  - \usepackage{amsfonts}
  - \usepackage{amssymb}
  - \usepackage[version=4]{mhchem}
  - \usepackage{stmaryrd}
  - \usepackage{graphicx}
  - \usepackage[export]{adjustbox}
output: pdf_document
---

1. Suppose that the amount of time teenagers spend weekly working at part-time jobs is normally distributed with a mean of 300 minutes and standard deviation of 40 minutes. Suppose that we sampled this population with a sample size of $n$ and the average of the sample is $\bar{X}_n=360$. Construct confidence intervals for the population mean with the following confidence levels and sample sizes:

> a. Does the CI become larger or smaller as the confidence level increases?

>>  **\underline{Answer:}**

>> We first need to figure out the $z_{\alpha/2}$. For 90\% CI,  $z_{\alpha/2}=1.645$. For 95\% CI,  $z_{\alpha/2}=1.96$. For 99\% CI,  $z_{\alpha/2}=2.575$. 

>> The confidence interval for $\mu$ can be constructed as $\bar{x}_n \pm z_{\alpha/2}\frac{\sigma}{\sqrt n}$. Therefore, for $n=9$ and $90\%$ confidence level:

$$
\bar{x}_n \pm z_{\alpha/2}\frac{\sigma}{\sqrt n}= 360\pm1.645\times\frac{36}{\sqrt 9}=360\pm 19.74= (340.26, \; 379.74)
$$

>> Using similar calculation, we get: 


\begin{center}
\begin{tabular}{|c|c|c|}
\hline
Confidence Level& $\quad \quad n=9 \quad \quad$ & $\quad \quad n=25 \quad \quad$\\
\hline
90\% &(340.26, 379.74) & (348.156, 371.844) \\
95\% & (336.48, 383.52) & (345.888, 374.112) \\
99\% & (329.1, 390.9) & (341.46, 378.54) \\
\hline
\end{tabular}
\end{center}

\  

> b. Does the CI become larger or smaller as the confidence level increases?

>> **\underline{Answer:}**

>> It becomes wider (larger). It makes sense since in the formula, $z_{\alpha/2}$ is in the numerator, therefore as $z_{\alpha/2}$ gets bigger $z_{\alpha/2}\frac{\sigma}{\sqrt n}$ becomes bigger 

\  

> c. Does the CI become larger or smaller as the sample size increases?

>> **\underline{Answer:}**

>> It shrinks (becomes smaller). It makes sense since in the formula, $n$ is in the denominator, therefore as $n$ gets bigger $\frac{\sigma}{\sqrt n}$ becomes smaller. 

\  


> d. With fixed confidence level and sample size, would the CI become larger/smaller/not change if the sample mean were smaller than 360?

>> **\underline{Answer:}**

>> It won't change since the width of the confidence interval depends only on confidence level and sample size. Therefore, the confidence interval will only **shift** when we change the sample mean.

\vspace{2cm}

2. A sample of 121 cans of coffee showed an average weight of 16 ounces and a standard deviation of $1$ ounces. Find an 80\%  and a 98\% confidence interval for the population mean.

> **\underline{Answer:}**

> Since $\sigma$ is unknown, We must use $t$-distribution. $df=n-1= 121-1=120$. We note that for a $80\%$ CI, we need to find $t_{0.2/2}=t_{0.1, df=120}=1.289$ and for $98\%$ CI, we need to find $t_{0.02/2}=t_{0.01, df=120}=2.358$.

> The 80% CI: $\bar{x} \pm t_{\alpha/2}\frac{s}{\sqrt n}= 16 \pm 1.289\times \frac{1}{\sqrt{121}}= (15.88, 16.12)$.

> The 98% CI: $\bar{x} \pm t_{\alpha/2}\frac{s}{\sqrt n}= 16 \pm 2.358\times \frac{1}{\sqrt{121}}= (15.79, 16.21)$.


\vspace{2cm}

3. Among 81 individuals sampled from the population, 24 smokers were observed. 

> a. Develop the $90 \% \mathrm{Cl}$ for the population proportion.

>>  **\underline{Answer:}**

>> $\hat{p}=\frac{24}{81}=0.2963$. Therefore,  $E=z_{\alpha / 2} \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}= 1.645 \times 0.0507 = 0.0835$

>> Now we can find the 90 \% CI as $\hat{p} \pm E=0.2963 \pm 0.0835=(0.2128,0.3798)$

\  

> b. If now you have a new sample of 150 individuals, determine an interval for the number of smokers based on your answer from question 3.

>>  **\underline{Answer:}**

>> If we know the true proportion $\frac{x}{N}$ of smokers is between $(0.2128,0.3798)$ then number of smokers among 150 people is $150 \times$ (0.2128, 0.3798)= (31.92, 56.97). But since we want the **number** of smokers (i.e. an integer), this should be an integer. We need to round it to (31, 57).  


