---
title: "Worksheet 5 Solution"
author: "Fred Azizi"
date: "2023-10-17"
output: pdf_document
---

1. 4 candidates are running for mayor; Adams, Brown, Collins and Dalton (We assume one of the candidates is going to win, there is no run off). The following probabilities are assigned:

$$P[ \text{Adams wins} ]=0.42 \quad P[ \text{Brown wins} ]=0.09$$

$$P[\text{Collins wins}]=0.27 \quad P[\text{Dalton wins}]=0.22$$

>Determine the probabilities for the following events (use 2 decimal places):

> a. Adams loses.

>> **\underline{Answer:}**

>> Use the complement Rule. 

>> $P[$ Adams lose $]=1$ - P[Adams wins] $=1-0.42=0.58$.


> b. Either Brown or Dalton wins.

>> **\underline{Answer:}**

>> Note that only one can win, therefore probability of both of them winning ($P$( brown win $\cap$ Dalton win)=0). Use the addition rule:

$$
P[\text{Brown win}]+P[\text{Dalton win}]=0.09+0.22=0.31
$$

> c. Adams, Brown, or Collins wins.

>> **\underline{Answer:}**

>> Two options. First one is the use of complement rule:

>> $P$[Adams wins or Brown wins or Collins wins $]=1-P$ [Dalton win$]=1-0.22=0.78$ 

>> Or user addition rule considering that probability of all intersections are zero.

>> $P[$Adams wins or Brown wins or Collins wins]= $P[$Adams wins$]$+$P[$Brown wins$]$+$P[$Collins wins$]$=$0.42+0.09+0.27=0.78$.

\  

2. $P[A]=0.30$ and $P[B]=0.40$. If $A$ and $B$ are mutually exclusive events, what is $P[A \cup B]$ ?

> **\underline{Answer:}**

> Since $A$ and $B$ are mutually exclusive events, then $P(A \cap B)=0$. Using the addition rule: 
 
$$
P(A \cup B)=P(A)+P(B)-P(A \cap B)
$$
$$
\quad=P(A)+P(B)-0=0.30+0.40=0.7 .
$$

\  

3. $P[A]=0.60$ and $P[B]=0.70$. If $A$ and $B$ are independent events, what is $P[A \cup B]$ ?

> **\underline{Answer:}**

> Since $A$ and $B$ are independent events, then $P(A \cap B)=P(A) \cdot P(B)$. Using the addition rule again: 

$$
P(A \cup B)=P(A)+P(B)-P(A \cap B)
$$
$$
P(A \cup B)=P(A)+P(B)-P(A)P(B)=0.6+0.7- .42=0.88
$$
\  


4. Assume you have applied for two scholarships, a Merit scholarship (M) and an Athletic
scholarship (A). The probability that you receive an Athletic scholarship is $0.18$. The probability of receiving both scholarships is $0.11$. The probability of getting at least one of the scholarships is 0.3. (i.e. $P(A)=0.18$, $P(A \cap M)=0.11$, and $P(A \cup M)=0.3$.)

> (a) What is the probability that you will receive a Merit scholarship?

>> **\underline{Answer:}**

$$
P(A \cup M)=P(A)+P(M)-P(A \cap M)
$$

$$\Rightarrow 0.3=0.18+P(M)-0.11 \Rightarrow P(M)=0.23$$

\  

> (b) Are events $\mathrm{A}$ and $\mathrm{M}$ mutually exclusive? Why or why not? Explain.

>> **\underline{Answer:}**

>> $P(A \cap M) \neq 0 \Rightarrow A$ and $M$ are not mutually exclusive.

\  

> (c) Are the two events $\mathrm{A}$, and $\mathrm{M}$, independent? Explain, using probabilities.

>> **\underline{Answer:}**

>> $P(A \cap M)=0.11$. But $P(A) \cdot P(M)=0.0414$. Therefore, $P(A \cap M) \neq P(A) \cdot P(M)$. Hence $A$ and $M$ are not independent.

\  


> (d) What is the probability of receiving the Athletic scholarship given that you have been awarded the Merit scholarship?

>> **\underline{Answer:}**

$$P(A \mid M)=\frac{P(A \cap M)}{P(M)}=\frac{0.11}{0.23}=0.4783$$

\  

5.  $60 \%$ of the student body at UTC is from the state of Tennessee (T), 30\% are from other states $(\mathrm{O})$, and the remainder constitutes international students (I). Twenty percent of students from Tennessee lives in the dormitories, whereas, $50 \%$ of students from other states live in the dormitories. Finally, $80 \%$ of the international students live in the dormitories.

> (a) What percentage of UTC students lives in the dormitories?

> (b) Given that a student lives in the dormitory, what is the probability that they are an international student?

> (c) Given that a student does not live in the dormitory, what is the probability that they are an international student?

> **\underline{Answer:}**

> (a)

> $P(T)=0.6, P(O)=0.3, P(I)=0.1.$

> $P(D \mid T)=0.2\rightarrow P(D^{c} \mid T)=1-P(D \mid T)=0.8$. $P(D \mid O)=0.5 \rightarrow P(D^{C} \mid O)=0.5$. And $P(D \mid I)=0.8 \rightarrow P(D^C \mid I)=0.2$.

\begin{align}
P(D)&=P(D \cap T)+P(D \cap O)+P(D \cap I)\notag\\
&= P(D \mid T) \times P(T)+P(D \mid O) \times P(O)+P(D \mid I) \times P(I) \notag \\
&= 0.2 \times 0.6+0.5 \times 0.3+0.8 \times 0.1 \notag\\
&=0.12+0.15+0.08=0.35 \notag
\end{align}

> (b) $P(I \mid D)=\frac{P(I \cap D)}{P(D)}=\frac{0.8 \times 0.1}{0.35}=0.229$. Note that for $P(I \cap D)$, we used what we had in the calculation of part a.

>> Alternatively, using Bayes rule: $P(I \mid D)=\frac{P(D \mid I) \cdot P(I)}{P(D)}=\frac{0.8 \times 0.1}{0.35}=0.229$.

> (c)

$$P\left(I \mid D^{c}\right)=\frac{P\left(I \cap D^{c}\right)}{P\left(D^{c}\right)}=\frac{P\left(D^{c} \mid I\right) \cdot P(I)}{P\left(D^{c}\right)}=\frac{P\left(D^{c} \mid I\right) \cdot P(I)}{1-P\left(D\right)}$$
$$
=\frac{0.2 \times 0.1}{0.65}={0.0308}
$$


\newpage

6. A survey asked 100 residents in a town whether they are smokers. Given the following information on the residents' response:

\begin{center}
\begin{tabular}{|l|l|l|l|}
\hline &  Daily Workout & No daily workout & Total \\
\hline Non-smoker & 40 & 30 & 70 \\
\hline Smoker & 20 & 10 & 30 \\
\hline Total & 60 & 40 & 100 \\
\hline
\end{tabular}
\end{center}

> (a) Find the joint probability table.

> (b) What is the probability that a randomly selected resident worksout daily?

> (c) What is the probability that a randomly selected resident doesn't workout daily?

> (d) What is the probability that a randomly selected resident worksout daily and is a smoker?

> (e) What is the probability that a randomly selected resident worksout daily or is a smoker?

> (f) A randomly selected resident doesn't workout daily. What is the probability that the resident is a smoker?

> **\underline{Answer:}**

> (a)

$$\begin{array}{cccc}\text { }&\text{DW} & \text { NDW } & \text { Total } \\NS & 0.4 & 0.3 & 0.7 \\ S & 0.2 & 0.1 & 0.3 \\\text{Total} & 0.6 & 0.4 & 1\end{array}$$

> (b) $P(DW)=0.6$.

> (c) $P(NDW)=1-P(DW)=0.4$

> (d) $P(DW \cap S)=0.2$

> (e)

$$
\begin{aligned}
P(DW \cup S)=P(DW)+P(S)-P(DW \cap S) &=0.6+0.3-0.2 \\
&=0.7
\end{aligned}
$$

> (f) $P(S|NDW)=\frac{P(S \cap NDW)}{P(NDW)}=\frac{0.1}{0.4}=0.25$
