---
title: "Worksheet 6"
author: "Fred Azizi"
date: "2022-10-17"
output: pdf_document
---

1. The number of pizzas delivered to university students each month is a random variable with the following probability distribution.

\begin{center}
\begin{tabular}{|l|l|l|l|l|}
\hline $\mathrm{X}$ & 0 & 1 & 2 & 3 \\
\hline $\mathrm{P}(\mathrm{x})$ & $0.1$ & $0.3$ & $0.4$ & $0.2$ \\
\hline
\end{tabular}
\end{center}

> (a) Find $\mathrm{P}(\mathrm{X} \leq 2)$.

> (b) $\mathrm{P}(1 \leq \mathrm{X} \leq 2)$.

> (c) Determine the mean and variance of $X$.

> (d)  Calculate the mean and sd of $Y=3X+4$.
\newpage


2. The number of persons living per household in a city was collected and were summarized. The frequency table is given below:

\begin{center}
\begin{tabular}{|l|l|l|l|l|l|l|l|}
\hline Number of persons & 1 & 2 & 3 & 4 & 5 & 6 & 7 \\
\hline Number of households (millions) & $3.1$ & $4.5$ & $3.8$ & $2.5$ & $2.4$ & $2.5$ & $1.2$ \\
\hline
\end{tabular}
\end{center}

> Define $X$ as the number of people per household.


> (a) Write down the probability distribution of $X$.

> (b) Find $P[X \geq 4]$

> (c) Find $\mathrm{P}[2 \leq \mathrm{X}<4]$


\newpage

3. Indicate whether each random variable is Binomial, Poisson or neither:

> a. A random variable $X$ counts the number of visits to a webpage in a one-hour period.

> b. A random variable $X$ counts the number of defectives in a sample of 100 stamps. 

> c. A random variable $X$ counts the number of hearts drawn from a well shuffled deck of 52 playing cards if 10 cards were drawn one at a time without replacement. 

> d. A random variable $X$ counts the number of hearts drawn from a well shuffled deck of 52 playing cards if 10 cards were drawn with replacement.

\newpage

4. 5 students are giving a make-up quiz. The probability of any of them scoring more than 25 is $0.6$. Let $X$ be the number of students who get over 25.

> a. Identify the distribution of $X$ and its parameters.



> b. What is the probability that none of the students score over 25 ?



> c. What is the probability that at least one of them score over 25 ?


> d. What is the probability that all of them score over 25 ?

\newpage

5. A six-sided die is rolled 6 times. Let $X$ denote the number of times an even number showed up.

> a. What is the probability of the event happening? That is, the probability of getting an even number. 

> b. What distribution will $X$ follow? Identify the parameters.

> c. Calculate $P[X=2]$.

> e. Calculate $P[0 \leq X<3]$

\newpage


6. Acme Corporation's helpdesk gets 4 calls per day on average. They think the number of calls follows a Poisson distribution. 

> a. What is the probability that they get 3 calls or less on a given day?

> b. What is the probability that they get no calls on given day?

> c. What is the probability that they get exactly 3 calls?

> d. What is the expected number of calls in a week? 

> e. What is the standard deviation for calls in a day?


\newpage

7. The number of flaws in an optic fiber cable follows a Poisson Distribution. The average number of flaws in $50 \mathrm{~m}$ is $1.5$. Let $x=$ average number of  flaws in $50 \mathrm{~m}$.

> a. What is the probability of exactly 2 flaws in $100 \mathrm{~m}$ ?

> b. What is the probability of 3 flaws or less in $150 \mathrm{~m}$ ?

> c. What is the probability of exactly one flaw in the first $50 \mathrm{~m}$ and exactly one flaw in the next $50 \mathrm{~m}$?